# Inspired by https://github.com/NotCookey/Pyinstaller-Github-Actions

name: Build

on:
  push:
    branches:
      - main

env:
  # TODO rem
  #VERSION: '0.1.4'
  APP_NAME: 'BoreMapper'
  MAIN_PY_FILE: 'boremapper/main.py'

# TODO: put tags back
#    tags:
#      - 'v*.*.*'
#  pull_request:
#    branches: [ main ]

jobs:
  
  build-windows:
    runs-on: 'windows-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Needed for extract-version-from-tag-action
          
      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.3.0
      
      - name: Process version
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "VERSION=${env:MAJOR}.${env:MINOR}.${env:PATCH}"
      
      # TODO: use APP_DIR instead of boremapper/
      # TODO rem cat?
      - name: Write version
        run: |
          echo "VERSION = '${env:VERSION}'" > boremapper/version.py
          echo "Version file contents:"
          cat boremapper/version.py

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14.x
          #architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
        
      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller ${{ env.MAIN_PY_FILE }}

      - name: Create artifact
        uses: actions/upload-artifact@v6
        with:
          name: '${{ env.APP_NAME }}-${{ env.VERSION }}-windows'
          path: dist/

      - name: List the dist folder
        run: |
          ls -R dist/

  build-linux:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Needed for extract-version-from-tag-action

      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.3.0

      - name: Process version
        run: |
          echo "VERSION=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV
      
      # TODO: use APP_DIR instead of boremapper/
      # TODO rem cat?
      - name: Write version
        run: |
          echo "VERSION = '$VERSION'" > boremapper/version.py
          echo "Version file contents:"
          cat boremapper/version.py

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14.x
          #architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller ${{ env.MAIN_PY_FILE }}

      - name: Create artifact
        uses: actions/upload-artifact@v6
        with:
          name: '${{ env.APP_NAME }}-${{ env.VERSION }}-linux'
          path: dist/

      - name: List the dist folder
        run: |
          ls -R dist/



#      - name: Create artifact - macOS
#        if: matrix.os == 'macos-latest'
#        uses: actions/upload-artifact@v6
#        with:
#          name: 'macos-executables'
#          path: dist/

#      - name: 'Install makensis'
#        if: matrix.os == 'windows-latest'
#        run: |
#          choco install nsis
#
#      - name: Create Windows NSIS installer
#        if: matrix.os == 'windows-latest'
#        run: |
#          & "${env:ProgramFiles(x86)}\NSIS\makensis.exe" /V4 /DVERSION=${{ env.VERSION }} "install.nsi"

#      - name: Create Windows NSIS installer
#        uses: EastDesire/makensis-action@publish
#        with:
#          script-file: "install.nsi"
#          # TODO
#          arguments: "/V4 /DVERSION=0.1.4"
#        env:
#          # TODO test
#          debug: true

#      - name: Create hashes
#        run: |
#          sha1sum ${{ env.APP_NAME }}-${{ env.VERSION }}.exe > ${{ env.APP_NAME }}-${{ env.VERSION }}.exe.sha1
#          sha1sum ${{ env.APP_NAME }}-${{ env.VERSION }}-Setup.exe > ${{ env.APP_NAME }}-${{ env.VERSION }}-Setup.exe.sha1
#          cat ${{ env.APP_NAME }}-${{ env.VERSION }}.exe.sha1
#          cat ${{ env.APP_NAME }}-${{ env.VERSION }}-Setup.exe.sha1
#          
#      - name: Upload artifacts
#        uses: actions/upload-artifact@v6
#        with:
#          name: Windows Build
#          if-no-files-found: error
#          path: |
#            ${{ env.APP_NAME }}-${{ env.VERSION }}.exe
#            ${{ env.APP_NAME }}-${{ env.VERSION }}.exe.sha1
#            ${{ env.APP_NAME }}-${{ env.VERSION }}-Setup.exe
#            ${{ env.APP_NAME }}-${{ env.VERSION }}-Setup.exe.sha1

#  release:
#    name: "Create GitHub release"
#    needs: [ build-windows ]
#    runs-on: ubuntu-latest
#    if: startswith(github.ref, 'refs/tags/v')
#    
#    steps:
#      - uses: actions/checkout@v6
#    
#      - name: Download and extract artifacts
#        uses: actions/download-artifact@v8
#        with:
#          path: artifacts
#    
#      - name: List files
#        run: |
#          ls -R
#    
#      - name: Add files to GitHub release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: |
#            ${{ github.workspace }}/artifacts/Windows Build/${{ env.APP_NAME }}-${{ env.VERSION }}.exe
#            ${{ github.workspace }}/artifacts/Windows Build/${{ env.APP_NAME }}-${{ env.VERSION }}.exe.sha1
#            ${{ github.workspace }}/artifacts/Windows Build/${{ env.APP_NAME }}-${{ env.VERSION }}-Setup.exe
#            ${{ github.workspace }}/artifacts/Windows Build/${{ env.APP_NAME }}-${{ env.VERSION }}-Setup.exe.sha1
#
#      - name: Create GitHub release
#        uses: Roang-zero1/github-create-release-action@v3
#        with:
#          update_existing: true
#          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}