# Inspired by https://github.com/NotCookey/Pyinstaller-Github-Actions

name: Build

on:
  push:
    tags:
      - 'v*.*.*'

env:
  APP_NAME: 'BoreMapper'
  APP_DIR: 'boremapper/'
  MAIN_PY_FILE: 'boremapper/main.py'

jobs:
  
  build-windows:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: 'windows-latest'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Needed for extract-version-from-tag-action
          
      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.3.0

      - name: Process version
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "VERSION=${env:MAJOR}.${env:MINOR}.${env:PATCH}"
      
      - name: Write version file
        run: |
          echo "VERSION = '${env:VERSION}'" > "${env:APP_DIR}version.py"
          echo "Version file contents:"
          cat "${env:APP_DIR}version.py"

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14.x
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
        
      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller ${{ env.MAIN_PY_FILE }}

      - name: Create artifact
        uses: actions/upload-artifact@v6
        with:
          name: '${{ env.APP_NAME }}-${{ env.VERSION }}-windows'
          path: dist/

      - name: List the dist folder
        run: |
          ls -R dist/

  build-linux:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: 'ubuntu-latest'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Needed for extract-version-from-tag-action
          
      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.3.0

      - name: Process version
        run: |
          echo "VERSION=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV
      
      - name: Write version file
        run: |
          echo "VERSION = '$VERSION'" > "${APP_DIR}version.py"
          echo "Version file contents:"
          cat "${APP_DIR}version.py"

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14.x
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller ${{ env.MAIN_PY_FILE }}

#      - name: Create hashes
#        run: |
#          sha1sum "${{ env.APP_NAME }}-${{ env.VERSION }}-linux" > "${{ env.APP_NAME }}-${{ env.VERSION }}-linux.sha1"
#          cat "${{ env.APP_NAME }}-${{ env.VERSION }}-linux.sha1"

      - name: Create artifact
        uses: actions/upload-artifact@v6
        with:
          name: '${{ env.APP_NAME }}-${{ env.VERSION }}-linux'
          path: dist/

      - name: List the dist folder
        run: |
          ls -R dist/

  release:
    needs:
      - build-windows
      - build-linux
    runs-on: ubuntu-latest
    if: startswith(github.ref, 'refs/tags/v')
    
    steps:
      - uses: actions/checkout@v6
        
      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.3.0

      - name: Process version
        run: |
          echo "VERSION=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV
      
      - name: Download and extract artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
    
      - name: List files
        run: |
          ls -R
    
      - name: Add files to GitHub release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ${{ github.workspace }}/artifacts/${{ env.APP_NAME }}-*

      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@v3
        with:
          update_existing: true
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_RELEASES }}