# Inspired by https://github.com/Erriez/pyside6-nuitka-deployment/blob/master/.github/workflows/build-release.yml

name: Build and release

on:
  push:
    branches: [ main ]
# TODO: put tags back
#    tags:
#      - 'v*.*.*'
#  pull_request:
#    branches: [ main ]

env:
  # TODO rem
  RELEASE_VERSION: 'v0.1.4'

jobs:
#  build-linux:
#    runs-on: ubuntu-latest
#    
#    steps:
#      - uses: actions/checkout@v6
#      TODO
      
  build-windows:
    runs-on: windows-2025
    
    steps:
      - uses: actions/checkout@v6
        
#      - name: Set env vars
#        run: |
#          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
#          echo "GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
        
      # TODO: rem?
      - name: Check vars
        run: |
          echo "RELEASE_VERSION=$RELEASE_VERSION"
          echo "env.RELEASE_VERSION=${{ env.RELEASE_VERSION }}"
          echo "GIT_TAG=$GIT_TAG"
      
      # TODO: move down
      - name: 'Install makensis'
        run: choco install nsis

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
            
      - name: Setup virtualenv
        run: |
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
          
      # TODO: use APP_DIR instead of boremapper/
      # TODO rem cat?
      - name: Write version
        run: |
          echo "VERSION = '$RELEASE_VERSION'" > boremapper/version.py
          echo "Version file contents:"
          cat boremapper/version.py
          
      - name: Build Windows executable
        run: |
          make build-windows
          
      - name: Create Windows NSIS installer
        # TODO: variable into DVERSION
        run: |
          & "${env:ProgramFiles(x86)}\NSIS\makensis.exe" /V4 /DVERSION=0.1.4 "install.nsi"
          
#      - name: Create Windows NSIS installer
#        uses: EastDesire/makensis-action@publish
#        with:
#          script-file: "install.nsi"
#          # TODO
#          arguments: "/V4 /DVERSION=0.1.4"
#        env:
#          # TODO test
#          debug: true

      #- name: Create Windows NSIS installer
      #  uses: joncloud/makensis-action@v5.0
      #  with:
      #    script-file: "install.nsi"
      #    # TODO
      #    arguments: "/V4 /DVERSION=0.1.4"
      #  env:
      #    # TODO test
      #    debug: true
          
      - name: Create hashes
        run: |
          sha1sum BoreMapper.exe > BoreMapper.exe.sha1
          sha1sum setup.exe > setup.exe.sha1
          cat BoreMapper.exe.sha1
          cat setup.exe.sha1
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Windows Build
          if-no-files-found: error
          path: |
            BoreMapper.exe
            BoreMapper.exe.sha1
            setup.exe
            setup.exe.sha1

  release:
    name: "Create GitHub release"
    needs: [ build-windows ]
    runs-on: ubuntu-latest
    if: startswith(github.ref, 'refs/tags/v')
    
    steps:
      - uses: actions/checkout@v6
    
      - name: Download and extract artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
    
      - name: List files
        run: |
          ls -R
    
      - name: Add files to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/artifacts/Windows Build/BoreMapper.exe
            ${{ github.workspace }}/artifacts/Windows Build/BoreMapper.exe.sha1
            ${{ github.workspace }}/artifacts/Windows Build/setup.exe
            ${{ github.workspace }}/artifacts/Windows Build/setup.exe.sha1

      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@v3
        with:
          update_existing: true
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}